export type Language = 'en' | 'zh-CN' | 'zh-TW';

export const translations: Record<Language, any> = {
  'en': {
    appName: 'Aura Weather',
    searchPlaceholder: 'Search global cities...',
    feelsLike: 'Feels like',
    wind: 'Wind',
    humidity: 'Humidity',
    uvIndex: 'UV Index',
    aqi: 'AQI',
    hourlyForecast: 'Hourly Forecast',
    dailyForecast: '7-Day Forecast',
    aiAdvice: 'AI Travel Advice',
    loadingAI: 'Summoning AI insights...',
    lifestyle: 'Lifestyle Insights',
    dressing: 'Dressing Index',
    carWash: 'Car Wash Index',
    sports: 'Outdoor Sports',
    uvProtection: 'UV Protection',
    severeWeather: 'Severe Weather Watch',
    viewRadar: 'View Radar',
    weatherCalendar: 'Weather Almanac',
    productivityScore: 'Productivity',
    optimizedSchedule: 'Optimized via AI',
    currentLocation: 'Current Location',
    footer: 'Data powered by Open-Meteo & Gemini AI',
    today: 'Today',
    recentSearches: 'Recent Searches',
    popularCities: 'Popular Cities',
    noResults: 'No cities found',
    clearHistory: 'Clear',
    uvLevels: { low: 'Low', moderate: 'Moderate', high: 'High', veryHigh: 'Very High' },
    aqiLevels: { healthy: 'Healthy', moderate: 'Moderate', unhealthy: 'Unhealthy' },
    dressingAdvice: 'Light cotton clothes are recommended for the heat.',
    carWashAdvice: 'Not ideal. Dust level is high today.',
    sportsAdvice: 'Great for jogging and cycling in the morning.',
    uvAdvice: 'The sun is strong. Ensure sunscreen and sunglasses are used.',
    weatherAlert: 'Potential for light thunderstorms in the late evening. Ensure patio furniture is secured.',
    aiSystemInstruction: 'You are a friendly weather assistant. Provide advice in English.'
  },
  'zh-CN': {
    appName: 'Aura 天气',
    searchPlaceholder: '搜索全球城市...',
    feelsLike: '体感温度',
    wind: '风速',
    humidity: '湿度',
    uvIndex: '紫外线指数',
    aqi: '空气质量',
    hourlyForecast: '逐小时预报',
    dailyForecast: '未来7天预报',
    aiAdvice: 'AI 出行建议',
    loadingAI: 'AI 正在分析天气...',
    lifestyle: '生活指数',
    dressing: '穿衣指数',
    carWash: '洗车指数',
    sports: '运动建议',
    uvProtection: '防晒指南',
    severeWeather: '恶劣天气预警',
    viewRadar: '查看雷达图',
    weatherCalendar: '天气日历',
    productivityScore: '生产力值',
    optimizedSchedule: 'AI 优化建议',
    currentLocation: '当前位置',
    footer: '数据由 Open-Meteo 和 Gemini AI 提供',
    today: '今天',
    recentSearches: '历史搜索',
    popularCities: '热门城市',
    noResults: '未找到城市',
    clearHistory: '清空',
    uvLevels: { low: '低', moderate: '中等', high: '高', veryHigh: '极高' },
    aqiLevels: { healthy: '优', moderate: '良', unhealthy: '中度污染' },
    dressingAdvice: '天气炎热，建议穿着轻便棉质衣物。',
    carWashAdvice: '不宜洗车，今日空气中浮尘较多。',
    sportsAdvice: '晨间非常适合慢跑或骑行。',
    uvAdvice: '紫外线较强，出门请做好防晒遮阳。',
    weatherAlert: '预计傍晚会有雷阵雨，请固定好阳台物品并记得带伞。',
    aiSystemInstruction: '你是一个友好的天气助手。请使用简体中文提供建议。'
  },
  'zh-TW': {
    appName: 'Aura 天氣',
    searchPlaceholder: '搜尋全球城市...',
    feelsLike: '體感溫度',
    wind: '風速',
    humidity: '濕度',
    uvIndex: '紫外線指數',
    aqi: '空氣品質',
    hourlyForecast: '逐小時預報',
    dailyForecast: '未來7天預報',
    aiAdvice: 'AI 出行建議',
    loadingAI: 'AI 正在分析天氣...',
    lifestyle: '生活指數',
    dressing: '穿衣指數',
    carWash: '洗車指數',
    sports: '運動建議',
    uvProtection: '防曬指南',
    severeWeather: '惡劣天氣預警',
    viewRadar: '查看雷達圖',
    weatherCalendar: '天氣日曆',
    productivityScore: '生產力值',
    optimizedSchedule: 'AI 優化建議',
    currentLocation: '目前位置',
    footer: '數據由 Open-Meteo 和 Gemini AI 提供',
    today: '今天',
    recentSearches: '歷史搜尋',
    popularCities: '熱門城市',
    noResults: '未找到城市',
    clearHistory: '清空',
    uvLevels: { low: '低', moderate: '中等', high: '高', veryHigh: '極高' },
    aqiLevels: { healthy: '優', moderate: '良', unhealthy: '中度污染' },
    dressingAdvice: '天氣炎熱，建議穿著輕便棉質衣物。',
    carWashAdvice: '不宜洗車，今日空氣中浮塵較多。',
    sportsAdvice: '晨間非常適合慢跑或騎行。',
    uvAdvice: '紫外線較強，出門請做好防曬遮陽。',
    weatherAlert: '預計傍晚會有雷陣雨，請固定好陽台物品並記得帶傘。',
    aiSystemInstruction: '你是一個友善的天氣助手。請使用繁體中文提供建議。'
  }
};
